name: kdm
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - tensorflow-probability>=0.24
  - tensorflow>=2.16
  - tf-keras>=2.16
  - ipykernel
  - matplotlib
  - pandas
  - networkx